# Updated opencost-app.yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: opencost
  namespace: argocd
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: opencost
  project: default
  source:
    repoURL: https://opencost.github.io/opencost-helm-chart
    targetRevision: 2.1.6
    chart: opencost
    helm:
      releaseName: opencost
      values: |
        service:
          type: ClusterIP
          port: 9003
        
        # Explicit configuration
        config:
          loadBalancer:
            cost: "0.00"
          cpu: "0.024"
          ram: "0.01"
          storage: "0.10"
          region: "local"
        
        prometheus:
          external:
            enabled: true
            url: "http://prometheus-server.prometheus-system.svc.cluster.local:80"
        
        # Ensure config is mounted properly
        extraEnv:
          - name: LOAD_BALANCER_COST
            value: "0.00"
        extraVolumeMounts:
          - name: pricing-config
            mountPath: /models/custom
        extraVolumes:
          - name: pricing-config
            configMap:
              name: opencost-pricing
        
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true