# opencost-app.yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: opencost
  namespace: argocd
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: opencost
  project: default
  source:
    repoURL: https://opencost.github.io/opencost-helm-chart
    targetRevision: 2.1.6
    chart: opencost
    helm:
      releaseName: opencost
      values: |
        service:
          type: ClusterIP
          port: 9003
        
        # Prometheus configuration
        prometheus:
          external:
            enabled: true
            url: "http://prometheus-server.prometheus-system.svc.cluster.local:80"
        
        # Pricing configuration to resolve warnings
        pricingConfigs:
          enabled: true
          config:
            CPU: "0.024"        # Cost per CPU core per hour
            GPU: "0.00"         # Cost per GPU per hour
            RAM: "0.01"         # Cost per GB of RAM per hour
            storage: "0.10"     # Cost per GB of storage per hour
            zoneNetworkEgress: "0.01"  # Cost per GB within zone
            regionNetworkEgress: "0.01" # Cost per GB within region
            internetNetworkEgress: "0.05" # Cost per GB internet egress
            loadBalancerCost: "0.00"    # Explicitly set LB cost to $0
        
        # Node labels for Minikube
        nodeLabels:
          topology.kubernetes.io/region: "local"
          kubernetes.io/hostname: "minikube"
        
        # Disable Kubecost components
        kubecostProductConfigs:
          enabled: false
        
        # Environment variables
        extraEnv:
          - name: PROMETHEUS_SERVER_ENDPOINT
            value: "http://prometheus-server.prometheus-system.svc.cluster.local:80"
          - name: AWS_REGION
            value: "local"  # Fallback region for Minikube
          - name: EXPORT_CSV_FILE
            value: ""       # Explicitly disable CSV export
        
        # Resource configuration
        resources:
          requests:
            memory: "512Mi"
            cpu: "200m"
          limits:
            memory: "1Gi"
            cpu: "500m"
        
        # Metrics configuration
        metricsConfigs:
          enabled: true
          config:
            cpu:
              enabled: true
              queryWindow: "3m"
            ram:
              enabled: true
              queryWindow: "3m"
        
        # Disable features not needed in Minikube
        cloudCost:
          enabled: false
        customCost:
          enabled: false
        
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
      - ApplyOutOfSyncOnly=true