apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: opencost
  namespace: argocd
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: opencost
  project: default
  source:
    repoURL: https://opencost.github.io/opencost-helm-chart
    targetRevision: 2.1.6
    chart: opencost
    helm:
      releaseName: opencost
      values: |
        service:
          type: ClusterIP
          port: 9003
        
        # Complete Pricing Configuration
        pricingConfigs:
          enabled: true
          config:
            # Load Balancer Specific Pricing
            loadBalancer:
              cost: "0.00"  # Base cost
              ingressDataCost: "0.01"  # Cost per GB of ingress data
              firstFiveForwardingRulesCost: "0.0"  # Cost for first 5 rules
              additionalForwardingRuleCost: "0.0"   # Cost per additional rule
            
            # General Resource Pricing
            CPU: "0.024"
            RAM: "0.01"
            storage: "0.10"
            zoneNetworkEgress: "0.01"
            regionNetworkEgress: "0.01"
            internetNetworkEgress: "0.05"
        
        # Other configurations...
        prometheus:
          external:
            enabled: true
            url: "http://prometheus-server.prometheus-system.svc.cluster.local:80"
        
        kubecostProductConfigs:
          enabled: false
        
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true