# opencost-application.yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: opencost
  namespace: argocd
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: opencost  # Create this namespace first
  project: default
  source:
    repoURL: https://github.com/opencost/opencost-helm-chart
    targetRevision: 1.107.0 # Use the latest stable version
    chart: opencost
    helm:
      releaseName: opencost
      values: |
        service:
          type: ClusterIP
        prometheus:
          external:
            enabled: true
            url: http://prometheus-prometheus-oper-prometheus.monitoring.svc.cluster.local:9090
    destination:
      server: https://kubernetes.default.svc
      namespace: opencost # The namespace where OpenCost will be installed
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true # Argo CD will create the 'opencost' namespace if it doesn't exist