# opencost-app.yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: opencost
  namespace: argocd
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: opencost
  project: default
  source:
    repoURL: https://opencost.github.io/opencost-helm-chart
    targetRevision: 2.1.6
    chart: opencost
    helm:
      releaseName: opencost
      values: |
        service:
          type: ClusterIP
          port: 9003
        
        # Complete Pricing Configuration
        pricingConfigs:
          enabled: true
          config:
            # Load Balancer Pricing (fixes the parsing error)
            loadBalancer:
              cost: "0.00"  # Base cost per hour
              ingressDataCost: "0.01"  # Cost per GB
              firstFiveForwardingRulesCost: "0.00"  # First 5 rules
              additionalForwardingRuleCost: "0.00"  # Each additional rule
            
            # Required Default Pricing
            CPU: "0.024"
            RAM: "0.01"
            storage: "0.10"
        
        # Ensure config is mounted properly
        extraVolumeMounts:
          - name: pricing-config
            mountPath: /etc/opencost
        extraVolumes:
          - name: pricing-config
            configMap:
              name: opencost-pricing
        
        # Other configurations
        prometheus:
          external:
            enabled: true
            url: "http://prometheus-server.prometheus-system.svc.cluster.local:80"
        
        kubecostProductConfigs:
          enabled: false
        
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true