apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: opencost
  namespace: argocd
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: opencost
  project: default
  source:
    repoURL: https://opencost.github.io/opencost-helm-chart
    targetRevision: 2.1.6
    chart: opencost
    helm:
      releaseName: opencost
      values: |
        service:
          type: ClusterIP
          port: 9003
        
        # Explicit Load Balancer Pricing
        pricingConfigs:
          enabled: true
          config:
            loadBalancer:
              cost: "0.00"  # Explicitly set to $0 for Minikube
            CPU: "0.024"
            RAM: "0.01"
            storage: "0.10"
        
        # Minikube-specific settings
        nodeLabels:
          topology.kubernetes.io/region: "local"
          kubernetes.io/hostname: "minikube"
        
        prometheus:
          external:
            enabled: true
            url: "http://prometheus-server.prometheus-system.svc.cluster.local:80"
        
        kubecostProductConfigs:
          enabled: false
        
        extraEnv:
          - name: PROMETHEUS_SERVER_ENDPOINT
            value: "http://prometheus-server.prometheus-system.svc.cluster.local:80"
          - name: AWS_REGION
            value: "local"
        
        # Disable LB monitoring for Minikube
        kubernetes:
          enableLoadBalancerMetrics: false
        
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true