# opencost-app.yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: opencost
  namespace: argocd
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: opencost
  project: default
  source:
    repoURL: https://opencost.github.io/opencost-helm-chart
    targetRevision: 2.1.6 # Use the latest stable version
    chart: opencost
    helm:
      releaseName: opencost
      values: |
        service:
          type: ClusterIP
        prometheus:
          external:
            enabled: true
            url: "http://prometheus-server.prometheus-system.svc.cluster.local:80"
        kubecostProductConfigs:
          enabled: false
        extraEnv:
          - name: PROMETHEUS_SERVER_ENDPOINT
            value: "http://prometheus-server.prometheus-system.svc.cluster.local:80"
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true