# opencost-app.yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: opencost
  namespace: argocd
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: opencost
  project: default
  source:
    repoURL: https://opencost.github.io/opencost-helm-chart
    targetRevision: 1.104.1
    chart: opencost
    helm:
      releaseName: opencost
      values: |
        service:
          type: ClusterIP
          port: 9003
        
        # Explicit pricing configuration
        pricingConfigs:
          enabled: true
          config:
            loadBalancer:
              cost: "0.00"
              ingressDataCost: "0.01"
              firstFiveForwardingRulesCost: "0.00"
              additionalForwardingRuleCost: "0.00"
            CPU: "0.024"
            RAM: "0.01"
            storage: "0.10"
        
        # Environment variable override
        extraEnv:
          - name: LOAD_BALANCER_COST
            value: "0.00"
          - name: CUSTOM_PRICING_CONFIG
            value: |
              {
                "loadBalancer": {
                  "cost": "0.00",
                  "ingressDataCost": "0.01",
                  "firstFiveForwardingRulesCost": "0.00",
                  "additionalForwardingRuleCost": "0.00"
                }
              }
        
        prometheus:
          external:
            enabled: true
            url: "http://prometheus-server.prometheus-system.svc.cluster.local:80"
        
        kubecostProductConfigs:
          enabled: false
        
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true