# opencost-app.yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: opencost
  namespace: argocd
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: opencost
  project: default
  source:
    repoURL: https://opencost.github.io/opencost-helm-chart
    targetRevision: 1.115.0
    chart: opencost
    helm:
      releaseName: opencost
      values: |
        service:
          type: ClusterIP
        prometheus:
          external:
            enabled: true
            url: "http://prometheus-kube-prometheus-prometheus.monitoring.svc.cluster.local:9090"
        kubecostProductConfigs:
          enabled: false
        extraEnv:
          - name: PROMETHEUS_SERVER_ENDPOINT
            value: "http://prometheus-kube-prometheus-prometheus.monitoring.svc.cluster.local:9090"
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true