# prometheus-application.yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus-stack
  namespace: argocd
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  project: default
  source:
    repoURL: https://prometheus-community.github.io/helm-charts
    targetRevision: 56.6.1 # Recommended stable version (75.x seems problematic)
    chart: kube-prometheus-stack
    helm:
      releaseName: prometheus
      values: |
        grafana:
          enabled: true
        alertmanager:
          enabled: false # Disable initially to reduce CRD load
        prometheus:
          enabled: true
          prometheusSpec:
            serviceMonitorSelectorNilUsesHelmValues: false
            ruleSelectorNilUsesHelmValues: false
            podMonitorSelectorNilUsesHelmValues: false
            probeSelectorNilUsesHelmValues: false
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true # Critical for large CRDs
      - ApplyOutOfSyncOnly=true # Prevents full-replace cycles