# prometheus-application.yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus-stack
  namespace: argocd
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring  # Create this namespace first
  project: default
  source:
    repoURL: https://github.com/prometheus-community/helm-charts
    targetRevision: 75.6.1
    chart: kube-prometheus-stack
    helm:
      releaseName: prometheus
      values: |
        grafana:
          enabled: true
        alertmanager:
          enabled: true
        prometheus:
          prometheusSpec:
            serviceMonitorSelectorNilUsesHelmValues: false
            ruleSelectorNilUsesHelmValues: false
            podMonitorSelectorNilUsesHelmValues: false
            probeSelectorNilUsesHelmValues: false
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true # Argo CD will create the 'monitoring' namespace if it doesn't exist